CREATE TABLE kanji(
   ideograma   VARCHAR(1) NOT NULL PRIMARY KEY
  ,onyomi      VARCHAR(10) NOT NULL
  ,kunyomi     VARCHAR(30)
  ,significado VARCHAR(255) NOT NULL
  ,exemplos    VARCHAR(255) NOT NULL
);
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('一','イチ','ひと～、ひと・つ','one; one radical (no.1)','一つ[ひとつ] one (general counter)一人[ひとり] one person一番[いちばん] first | best; most');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('七','シチ','なな、なな・つ、なの','seven','七つ[ななつ] seven (general counter)七日[なのか] the seventh day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('万','マン',NULL,'10,000; ten thousand','十万[じゅうまん] 100,000');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('三','サン','みっ・つ、み・つ','three','三つ[みっつ] three (general counter)三日[みっか] the third day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('上','ショウ、ジョウ','あ・がる、あ・げる、うえ、うわ～','above; up','上[あ]げる to raise; to elevate | to increase (price, quality, status, etc.)上手[じょうず] skillful; proficient; good (at)上着[うわぎ] coat; tunic; jacket; outer garment');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('下','カ、ゲ','さ・がる、さ・げる、した、くだ・さる','below; descend;; inferior; low','地下鉄[ちかてつ] subway廊下[ろうか] corridor; hallway靴下[くつした] socks');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('中','チュウ','うち、なか','center; in; inside; middle','中国[ちゅうごく] China');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('九','キュウ、ク','ここの、ここの・つ','nine','九つ[ここのつ] nine (general counter)九日[ここのか] the ninth day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('二','ニ','ふた・つ','two; two radical (no. 7)','二つ[ふたつ] two (general counter)二人[ふたり] two people; pair; couple二日[ふつか] second day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('五','ゴ','いつ、いつ・つ','five','五つ[いつつ] five (general counter)五日[いつか] the fifth day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('人','ジン、ニン','～と、～り、ひと','person','一人[ひとり] one person二人[ふたり] two people; pair; couple外国人[がいこくじん] foreigner; foreign citizenご主人[しゅじん] (hon) your husband');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('今','コン','いま','now','今年[ことし] this year今晩[こんばん] tonight今月[こんげつ] this month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('休','キュウ','やす・む','day off; rest; retire','休[やす]み rest | vacation; holiday休[やす]む to take a day off | to rest; to have a break夏休[なつやす]み summer vacation');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('会','カイ','あ・う','association; join; meet; meeting','会[あ]う to meet会社[かいしゃ] company');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('何','カ','なに、なん','what','何[なん]の料理[りょうり] What kind of food');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('先','セン','さき','ahead; before; future; previous','先月[せんげつ] last month先生[せんせい] teacher; doctor先週[せんしゅう] last week');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('入','ニュウ','い・る、い・れる、はい・る','enter; insert','入[い]れる to put in; to insert入[はい]る to enter; to go into | to join; to enroll入口[いりぐち] entrance; entry');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('八','ハチ','や、やっ・つ、や・つ、よう','eight; eight radical (no. 12)','八つ[やっつ] eight (general counter)八日[ようか] the eighth day of the month八百屋[やおや] greengrocer');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('六','ロク','む、むい、むっ・つ、む・つ','six','六つ[むっつ] six (general counter)六ひ[むいか] sixth day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('円','エン','まる・い','circle; round; yen','十円[じゅうえん] 10 yen');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('出','シュツ','だ・す、で・る','come out; exit; go out; leave; protrude; put out','出[だ]す to take out; to get out | to submit (e.g. thesis) | to send (e.g. letter)出[で]かける to go out (ex. on an outing); to set out出[で]る to leave; to exit; to go out;出口[でぐち] exit出来[でき]る to be able to do');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('分','フン、ブン','わ・かる、わ・かれる、わ・ける','degree; know; understand; minute of time; part','分[わ]かる to understand; to comprehend半分[はんぶん] half多分[たぶん] perhaps; probably自分[じぶん] myself; oneself～分[ぶん] minutes (unit of time) | counter for minutes');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('前','ゼン','まえ','before; in front','午前[ごぜん] morning; a.m.名前[なまえ] name | given name; first name');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('北','ホク','きた','north','北[きた] north');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('十','ジュウ、ジュッ','とお','ten','十個[じゅっこ] 10 small objects十日[とおか] the tenth day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('千','セン',NULL,'thousand','千[せん] thousand');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('午','ゴ',NULL,'11AM-1PM; noon; seventh sign of Chinese zodiac; sign of the horse','午前[ごぜん] morning; a.m.午後[ごご] afternoon; p.m.');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('半','ハン','なか・ば','half; middle; odd number; part-; semi-','半分[はんぶん] half');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('南','ナン','みなみ','south','南[みなみ] south');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('友','ユウ','とも','friend','友達[ともだち] friend; companion');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('口','ク、コウ','くち','mouth','入口[いりぐち] entrance; entry出口[でぐち] exit');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('古','コ','ふる・い','old','古[ふる]い old (not person); aged; stale');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('右','ウ、ユウ','みぎ','right','右[みぎ] right');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('名','ミョウ、メイ','な','distinguished; name','名前[なまえ] name | given name; first name平仮名[ひらがな] hiragana有名[ゆうめい] famous');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('四','シ','よん、よっ・つ、よ・つ','four','四つ[よっつ] four (general counter)四日[よっか] fourth day of the month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('国','コク','くに','country','外国[がいこく] foreign country外国人[がいこくじん] foreigner; foreign citizen');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('土','ト、ド','つち','earth; ground; soil','土曜日[どようび] Saturday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('外','ガイ','そと、はず・す、はず・れる、ほか','outside','外国[がいこく] foreign country外国人[がいこくじん] foreigner; foreign citizen');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('多','タ','おお・い','frequent; many; much','多分[たぶん] perhaps; probably');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('大','タイ、ダイ','おお・きい','big; large','大丈夫[だいじょうぶ] safe; all right; alright; OK大使館[たいしかん] embassy大切[たいせつ] important; necessary大勢[おおぜい] many people大学[だいがく] university; college');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('天','テン','あめ','heavens; imperial; sky','天気[てんき] weather');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('女','ジョ','おんな','female; woman','女[おんな]の子[こ] girl; young woman');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('子','シ、ス','こ','child','女[おんな]の子[こ] girl; young woman子供[こども] child; children帽子[ぼうし] hat男[おとこ]の子[こ] boy');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('学','ガク','まな・ぶ','learning; science; study','大学[だいがく] university; college学校[がっこう] school留学生[りゅうがくせい] exchange student');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('安','アン','やす・い','cheap; contented; low; peaceful; quiet; relax; rested','安[やす]い cheap; inexpensive');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('小','ショウ','ちい・さい','little; small','小[ちい]さい small; little; tiny小[ちい]さな small; little; tiny');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('少','ショウ','すく・ない、すこ・し','few; little','少[すく]ない few; a little少[すこ]し small quantity; little; few');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('山','サン','やま','mountain','沢山[たくさん] a lot; many; a large number **Not always written in kanji');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('川','セン','かわ','river','川[かわ] river');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('左','サ、シャ','ひだり','left','左[ひだり] left');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('年','ネン','とし','year','今年[ことし] this year再来年[さらいねん] year after next毎年[まいとし] every year; annually～年[ねん] year (unit of time) | counter for years');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('店','テン','みせ','shop; store','喫茶店[きっさてん] coffee shop; cafe');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('後','コウ、ゴ','あと、うし・ろ','back; behind; later','午後[ごご] afternoon; p.m.後[うし]ろ back; behind; rear');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('手','シュ、ズ','て、た','hand','上手[じょうず] skillful; proficient; good (at)下手[へた] unskillful; poor; awkward切手[きって] stamp (postage)手紙[てがみ] letterお手洗[てあら]い toilet; restroom');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('新','シン','あたら・しい、あら・た','new','新[あたら]しい new新聞[しんぶん] newspaper');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('日','ジツ、ニチ','か、び、ひ','counter for days; day; Japan; sun','七日[なのか] the seventh day of the month土曜日[どようび] Saturday日曜日[にちようび] Sunday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('時','ジ','どき、とき','hour; time','時々[ときどき] sometimes～時間[じかん] period of hours');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('書','ショ','か・く','write','図書館[としょかん] library葉書[はがき] postcard辞書[じしょ] dictionary');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('月','ガツ、ゲツ','つき','month; moon','一月[いちがつ] January今月[こんげつ] this month先月[せんげつ] last month月曜日[げつようび] Monday毎月[まいつき] every month');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('木','ボク、モク','き','tree; wood','木曜日[もくようび] Thursday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('本','ホン','もと','book; counter for long cylindrical things; origin; real; true','本当[ほんとう] truth; reality; actuality本棚[ほんだな] bookshelvese～本[ほん] counter for cylidrical objects');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('来','ライ','く・る','become; cause; come; due; next','来[く]る to come; to approach来月[らいげつ] next month来週[らいしゅう] next week');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('東','トウ','ひがし','east','東[ひがし] east');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('校','コウ',NULL,'correction; exam; printing; proof; school','学校[がっこう] school');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('母','ボ','はは','mother','お母[かあ]さん mother');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('毎','マイ',NULL,'every','毎年[まいとし] every year; annually毎日[まいにち] every day毎晩[まいばん] every night');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('気','キ、ケ',NULL,'air; atmosphere; mind; mood; spirit','元気[げんき] healthy; well; lively天気[てんき] weather病気[びょうき] illness; disease');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('水','スイ','みず','water','水曜日[すいようび] Wednesday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('火','カ','ひ、び','fire','火曜日[かようび] Tuesday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('父','フ','ちち','father','お父[とう]さん father');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('生','ショウ、セイ','うま・れる、う・む、い・かす、い・きる、い・ける、なま','birth; genuine; life','先生[せんせい] teacher; doctor生[う]まれる to be born生徒[せいと] student留学生[りゅうがくせい] exchange student誕生[たんじょう]日[び] birthday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('男','ダン','おとこ','male','男[おとこ]の子[こ] boy');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('白','ハク','しろ・い','white','白[しろ]い white面白[おもしろ]い interesting; fascinating');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('百','ヒャク、ビャク',NULL,'hundred','百[ひゃく] 100');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('目','モク','め','eye; favor; insight; look','目[め] eye');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('社','シャ','やしろ','association; company; firm','会社[かいしゃ] company');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('空','クウ','そら、あ・く、あ・ける','empty; sky; vacant; vacuum; void','空[そら] sky');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('立','リツ','た・つ、た・てる','stand up; erect; rise; set up','立[た]つ to stand; to rise立派[りっぱ] splendid; fine');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('耳','ジ','みみ','ear','耳[みみ] ear');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('聞','ブン','き・く','ask; hear; listen','聞[き]く to hear; to listen | to ask新聞[しんぶん] newspaper');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('花','カ','はな','flower','花瓶[かびん] (flower) vase');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('行','ギョウ、コウ','い・く、おこな・う、ゆ・く','go; act; carry out; line; row','行[い]く to go; to head (towards)旅行[りょこう] trip銀行[ぎんこう] bank飛行機[ひこうき] airplane');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('西','サイ、セイ','にし','west','西[にし] west');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('見','ケン','み・る、み・せる','look at; opinion; see; visible','見[み]せる to show; to display見[み]る to see; to look');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('言','ゲン、ゴン','い・う、こと','say; word','言[い]う to say; to utter言葉[ことば] word; phrase');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('話','ワ','はなし、はな・す','tale; talk','話[はな]す to talk; to speak; to converse電話[でんわ] phone call | telephone (device)');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('語','ゴ','かた・る','language; speech; word','英語[えいご] English');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('読','ドク','よ・む','read','読[よ]む to read');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('買','バイ','か・う','buy','買[か]う to buy買[か]い物[もの] shopping; purchased goods');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('足','ソク','あし、た・す、た・りる','be sufficient; counter for pairs of footwear; foot; leg','足[あし] leg');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('車','シャ','くるま','car','自動車[じどうしゃ] automobile自転車[じてんしゃ] bicycle電車[でんしゃ] train');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('週','シュウ',NULL,'week','今週[こんしゅう] this week先週[せんしゅう] last week来週[らいしゅう] next week毎週[まいしゅう] every week～週間[しゅうかん] period of weeks');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('道','トウ、ドウ','みち','course; district; journey; moral; road-way; street; teachings','道[みち] road');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('金','キン','かね','gold','金曜日[きんようび] Friday');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('長','チョウ','なが・い','leader; long; senior; superior','長[なが]い long (distance or time)');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('間','カン、ケン','あいだ、ま','interval; space','時間[じかん] time～週間[しゅうかん] period of weeks');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('雨','ウ','あめ','rain','雨[あめ] rain');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('電','デン',NULL,'electricity','電気[でんき]ストーブ electric heater電話[でんわ] phone call | telephone (device)電車[でんしゃ] train');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('食','ショク','た・べる、く・う','eat; food','食[た]べる to eat食[た]べ物[もの] food食堂[しょくどう] cafeteria');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('飲','イン','の・む','drink; smoke; take','飲[の]む to drink; to swallow; to take (medicine)飲[の]み物[もの] drink; beverage');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('駅','エキ',NULL,'station','駅[えき] train');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('高','コウ','たか・い、たか・まる、たか・める','expensive; high; tall','高[たか]い high; tall | expensive高校[こうこう] high school');
INSERT INTO kanji(ideograma,onyomi,kunyomi,significado,exemplos) VALUES ('魚','ギョ','さかな','fish','魚[さかな] fish');
